### ISSUE TITLE
Lint problem

### ISSUE THREAD

**Issue by huineng** [thenoseman/angular-aot-fixer-pug#1]
Really like your solution, i was looking for that , nevertheless got some lint warnings and could not compile using webpack.

i modified your code a bit in fixer.js
instead of 

    var fileContent = "export var tpl = \"" + pugContent.replace(/"/g,'\\"') + "\";";

i changed to 

    var fileContent = "export default `" + pugContent + "`;";

and then 

    import template from './templates/help.pug';
    @Component({
        template: template
    })

now it works as a charm

**Comment by thenoseman** [comment]
Yeah the fixer is quiet opinionated for my personal use :)
